version: '3.9'
services:
  app:
    build:
      context: ./    
      dockerfile: Dockerfile 
    container_name: app
    restart: unless-stopped
    volumes:
      - ./src:/app/src 
      - ./src/config:/app/config
      - ./src/models:/app/models
      - ./src/routes:/app/routes
      - ./src/migrations:/app/migrations
      - ./src/seeders:/app/seeders
      - ./stats:/app/stats
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on: 
      - ssh_tunnel
    environment:
      PORT: ${PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ssh_tunnel
      DB_PORT: 5445
    networks:
      - my_network
  ssh_tunnel:
    build:
      context: ./ssh
      dockerfile: Dockerfile
    container_name: ssh_tunnel
    restart: unless-stopped
    ports:
      - "5445:5445"
    stdin_open: true
    tty: true
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
