version: '3.9'
services:
  app:
    build:
      context: ./    
      dockerfile: Dockerfile 
    container_name: app
    restart: unless-stopped
    volumes:
      - ./src:/app/src 
      - ./src/config:/app/config
      - ./src/models:/app/models
      - ./src/routes:/app/routes
      - ./src/migrations:/app/migrations
      - ./src/seeders:/app/seeders
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on: 
      - mimic_db 
    environment:
      PORT: ${PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
  mimic_db: 
    image: postgres 
    container_name: mimic_db
    ports:
      - "5445:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - mimic_db-volume:/var/lib/postgresql/data 
volumes: 
  mimic_db-volume:
